language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
install:
  - pip install codecov coverage pytest==3.3.2 python_coveralls
  - pip install -U rbnf wisepy
  - python setup.py install

script:
  - coverage run --m tests
  # exclude bootstrap for ast transformations cannot be detected by coverage, causing incorrect report.
  - coverage report --omit=.\rbnf\bootstrap\rbnf.py

after_success:
  - codecov
  - coveralls